name: "Refresh SSL Cert From Asus DDNS Router Update"
version: 0.1.1
slug: "refresher_ssl_cert_from_asus_ddns_router_update"
description: "An Add-on that help refresh the SSL certificate under the /SSL folder from Asus Router DDNS"
startup: once
image: ghcr.io/strauby/refresher-ssl-cert-from-asus-ddns-router-{arch}
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - ssl:rw
  - config
environment:
  CONFIG_PATH: /data/options.json
options:
  sslFromAsusRouter:
    routerUser: null
    routerIp: null
    routerSshPort: 22
    rsaPrivateKeyPath: null
    keyFilePathOnRouter: null
    certFilePathOnRouter: null
schema:
  sslFromAsusRouter:
    routerUser: str
    routerIp: str
    routerSshPort: int
    rsaPrivateKeyPath: str
    keyFilePathOnRouter: str
    certFilePathOnRouter: str